workflows:
  android-release:
    name: Aura Production Build
    max_build_duration: 120

    environment:
      java: 17

      vars:
        GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Grant permission
        script: chmod +x gradlew

      - name: Clean
        script: ./gradlew clean

      - name: Build Debug APK
        script: ./gradlew assembleDebug

      - name: Build Release APK
        script: ./gradlew assembleRelease

      - name: Build AAB
        script: ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/mapping/**

    publishing:
      email:
        recipients:
          - your-email@example.com
